# website configs
title: Homepage of Loong
url: wangl-cc.github.io
license: >
  <a rel="license"
  href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative
  Commons License" style="border-width:0"
  src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" /></a><br />
  All works are licensed under a <a rel="license"
  href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons
  Attribution-ShareAlike 4.0 International License</a>.

description: >
  A website belongs to Long Wang for sharing some ideas.
  Thanks for your visit.

# author configs
author:
  name: Long Wang
  email: wangl.cc@outlook.com
  social_links:
    github: wangl-cc
  description: |
    Master student of theoretical evolutionary biology in Sun Yat-sen University.


# Other options
paginate: 5
paginate_path: "/post/page:num/"

show_excerpts: true

markdown: kramdown

plugins:
 - jekyll-seo-tag
 - jekyll-paginate

# vim:ts=2:sw=2
