title: Homepage of Loong
author: 'Long "Loong" Wang'
email: wangl.cc@outlook.com
description: >
  A website belongs to Long Wang for sharing some ideas.
  Thanks for your visit.

url: wangl-cc.github.io

# social links
github_username: wangl-cc

paginate: 5
paginate_path: "/post/page:num/"

show_excerpts: false

markdown: kramdown

plugins:
 - jekyll-seo-tag
 - jekyll-paginate

 # vim:ts=2:sw=2:tw=76
