# website configs
title: Homepage of Loong
url: wangl-cc.github.io
license: by-sa

description: >
  A website belongs to Long Wang for sharing some ideas.
  Thanks for your visit.

# author configs
author:
  name: Long Wang
  email: wangl.cc@outlook.com
  social_links:
    github: wangl-cc
    twitter: LoongWANG3
  description: |
    Master student of theoretical evolutionary biology in Sun Yat-sen University.


# Other options
paginate: 5
paginate_path: "/post/page:num/"

show_excerpts: true

markdown: kramdown

plugins:
 - jekyll-seo-tag
 - jekyll-paginate

# vim:ts=2:sw=2
