title: Homepage of Long
author: Long Wang
email: wangl.cc@outlook.com
description: >
  A website belongs to Long for sharing some ideas.
  Thanks for your visit.

url: wangl-cc.github.io

logo: /assets/logo.png
# social links
github_username:  wangl-cc

paginate: 5
paginate_path: "/post/page:num/"

show_excerpts: false

markdown: kramdown

plugins:
 - jekyll-seo-tag
 - jekyll-paginate

