# website configs
title: Homepage of Loong
url: wangl-cc.github.io
license: by-sa

description: >
  A website belongs to Loong Wang for sharing some ideas.
  Thanks for your visiting.

# author configs
author:
  name: Loong Wang
  email: wangl.cc@outlook.com
  social_links:
    github: wangl-cc
    twitter: LoongWANG3
  description: |
    Graduate student of theoretical evolutionary biology in SYSU, JuliaLang enthusiast.



# Other options
paginate: 5
paginate_path: "/post/page:num/"

show_excerpts: true

markdown: kramdown

plugins:
 - jekyll-seo-tag
 - jekyll-paginate

# vim:ts=2:sw=2
